### ISSUE TITLE
유저 스타일 커스터마이징을 위한 공식적 루트 추가 요망.

### ISSUE THREAD

**Issue by tnraro** [JJoriping/j-launcher#1]
[이 라인](https://github.com/JJoriping/j-launcher/blob/master/views/index.pug#L12)의 다음 줄에 `link(rel="stylesheet", href="./css/user.css")` 정도의 코드 한 줄만 추가해주시면 정말 도움이 되겠습니다.

**Comment by JJoriping** [comment]
제보 감사드립니다. 말씀하신 사안은 다음 릴리즈에서 반영될 예정입니다.
